### ISSUE TITLE
phpmd-ci target in build.xml does not report failures

### ISSUE THREAD

**Issue by melvin-ibuildings** [ibuildingsnl/qa-tools#10]
original created by mvdbos

Strangely, when running the full build through ant with build.xml, the phpmd-ci target doesn't report errors for some files, but not all, that have proven errors when running phpmd manually on that file or through the qa-tools.

**Comment by DRvanR** [comment]
Without a testcase this is impossible to reproduce. When encountering this issue, please leave a comment here with a testcase. Until then, closing this issue.
