### ISSUE TITLE
Allow JSHint installation without node 

### ISSUE THREAD

**Issue by melvin-ibuildings** [ibuildingsnl/qa-tools#12]
original created by DRvanR

Currently the JSHint configurator is set up to always test whether or not node is installed, and aborts if not, see [here][0]. This is all good *if you run this on your dev img*. From looking at the code it seems that it wants [to install JSHint on the machine][1]. This is nice for people not having JSHint installed or integrated their IDE, but is annoying if you run this locally and/or don't have node installed (because they install it later, or people might use the rulesets for CI only without the pre-commit hook).

Imo, the user should at least be prompted to make a decision about this, rather than denying installation immediately, a.e:
> JSHint cannot be installed since node is not installed, do you still want to continue configuring JSHint? (y\N)

[0]: https://github.com/ibuildingsnl/qa-tools/blob/master/src/Ibuildings/QA/Tools/Javascript/Configurator/JsHintConfigurator.php#L93
[1]: https://github.com/ibuildingsnl/qa-tools/blob/master/src/Ibuildings/QA/Tools/Javascript/Console/InstallJsHintCommand.php#L57

**Comment by DRvanR** [comment]
Superseded by https://github.com/ibuildingsnl/qa-tools/issues/69
