### ISSUE TITLE
QA-tools is not responsible for installation of binaries

### ISSUE THREAD

**Issue by melvin-ibuildings** [ibuildingsnl/qa-tools#14]
original created by mvdbos

The core tools and plugins will never install anything other than scripts (PHP, shell, etc.) and config files. If there are any binaries needed (such as PHP and git, or even jshint), we REQUIRE them:

QA Tools core REQUIRES: git and PHP
QA Tools PHP REQUIRES: php
QA Tools plugin Javascript REQUIRES: jshint, it doesn't even care what kind of jshint it is, as long as it is the right version and it is available in the path. 
- [ ] remove installation logic from JS tools

**Comment by DRvanR** [comment]
The JSHint detection/installation should be tackled when making the split into compontents (the [3.0][1] drive)

[1]: https://github.com/ibuildingsnl/qa-tools/milestones/3.0

**Comment by rjkip** [comment]
Will be tackled through version 3's architecture.
