### ISSUE TITLE
Let build install jshint dependency

### ISSUE THREAD

**Issue by melvin-ibuildings** [ibuildingsnl/qa-tools#15]
original created by lucasvanlierop

Instead of using composer to trigger installation of jshint let the build do the work.

Add the following target and let jshint targets deped on it (note that this is the parsed version of the xml)

```xml
<target name="install-jshint">
        <exec executable="${basedir}/bin/qa-tools">
            <arg line="install:jshint"/>
        </exec>
    </target>
```

**Comment by DRvanR** [comment]
Superseded by https://github.com/ibuildingsnl/qa-tools/issues/69
