### ISSUE TITLE
JSHint cyclomatic complexity default is low

### ISSUE THREAD

**Issue by melvin-ibuildings** [ibuildingsnl/qa-tools#18]
original created by DRvanR

Currently the default jshint.maxcomplexity is set to 3. To me this seems to be low. Not sure if it would be something to update by default to say 4 or 5, allowing:

``` js
if (/* something */) {
    /* do this */
} else {
    /* do that */
}

/* ALSO */
if (/* something else */) {
    /* do X */
} else {
    /* do Y */
}
```

**Comment by DRvanR** [comment]
After discussion, the default value will be increased to 5. This allows for a ternary operator, or the if/else structure as described above. This prevents trying to flatten code too much.

Should be done in the earliest possible release.

**Comment by rjkip** [comment]
No more effort will be put into 2.x. This enhancement has been noted in and will be superseded by https://github.com/ibuildingsnl/qa-tools-v3/issues/84
