### ISSUE TITLE
PHPMD excludes don't always work

### ISSUE THREAD

**Issue by melvin-ibuildings** [ibuildingsnl/qa-tools#19]
original created by mvdbos

Als een file expliciet genoemd wordt als te scannen source, wordt deze niet ge-exclude, ook al match hij een exlcude pattern. Dit komt dus alleen voor bij de pre-commit variant, want de ci-versie scant alleen het root src path

Zie hier: https://github.com/phpmd/phpmd/issues/102

Dit is lastig te fixen. Oplossing zou kunnen zijn om meer global excludes te doen, en deze dus al uit de changeset te houden binnen de qa-tools

**Comment by rjkip** [comment]
No more effort will be put into 2.x. Note added to related 3.x ticket https://github.com/ibuildingsnl/qa-tools/issues/79
