### ISSUE TITLE
Qa tools opsplitsen in verschillende composer packages

### ISSUE THREAD

**Issue by melvin-ibuildings** [ibuildingsnl/qa-tools#22]
original created by mvdbos
- Common (dependency voor alle andere)
- Drupal (conflicts PHP)
- Javascript
- Functional
- PHP (conflicts Drupal)

De InstallCommand van Common herkent welke packages zijn geïnstalleerd en vraagt of je die wil configureren. Runt dan de configurators van die packages.

**Comment by rjkip** [comment]
No longer relevant with oncoming 3.0 release.
