### ISSUE TITLE
qa-tools-common als framework

### ISSUE THREAD

**Issue by melvin-ibuildings** [ibuildingsnl/qa-tools#24]
original created by mvdbos

Common gebruikt een Renderer om de build.xml te genereren. Mochten we ooit iets anders willen, bijvoorbeeld Scrutinizer of Travis, dan zou alleen die Renderer aangepast moeten hoeven worden.

De verschillende configurators weten niets van renderen en manipuleren alleen de Settings. Die hoeven dan dus niet aangepast te worden.

Wel genereren ze eventueel hun eigen config files, zoals phpcs.xml

**Comment by rjkip** [comment]
Looks like this won't be needed anymore with the oncoming 3.0 release, correct?
