### ISSUE TITLE
Generate buildfiles in PHP

### ISSUE THREAD

**Issue by melvin-ibuildings** [ibuildingsnl/qa-tools#6]
original created by relaxnow

Buildfiles are currently in XML, which can get convoluted with complicated builds, as the QA tools are quick to generate, also [programming in XML is generally not a good idea](http://martinfowler.com/bliki/BuildLanguage.html).
Consider switching to a PHP buildfile alternative like:

- [Bob](https://github.com/CHH/bob)
- [Maiden](https://github.com/serby/maiden)
- [pake](https://github.com/indeyets/pake/wiki)
- [pantr](https://github.com/pago/pantr)
- [PHP Go](https://github.com/herrera-io/php-go)

[etc...](https://github.com/search?o=desc&q=php+build+tool&ref=cmdform&s=stars&type=Repositories)?

**Comment by DRvanR** [comment]
Closing this issue, made obsolete by #7
