### ISSUE TITLE
Find a good way to handle the JSHint installation/checking during installation/configuration

### ISSUE THREAD

**Issue by DRvanR** [ibuildingsnl/qa-tools#69]
See #11, #12  and #15.

When switching to separate packages for php/js etc, we should resolve the issue of properly detecting the jshint installation and making the jshint installation optional.

**Comment by rjkip** [comment]
Will be fixed when adding JS code style tool (https://github.com/ibuildingsnl/qa-tools-v3/issues/84) in a future 3.x release
