### ISSUE TITLE
JavaScript code styles

### ISSUE THREAD

**Issue by seggen-ibuildings** [ibuildingsnl/qa-tools#76]
For Symfony projects, we'd like to use the Airbnb style guide (which has a preset for ESLint). Drupal has its own style guide, including an ESLint example file: https://www.drupal.org/node/1955232.

I would like to suggest that we switch JSHint for ESLint and add a prompt to choose a coding style (offering at least Airbnb and Drupal).

**Comment by mroest** [comment]
:+1:

**Comment by rjkip** [comment]
:+1:

**Comment by melvin-ibuildings** [comment]
:+1:

**Comment by rjkip** [comment]
Will be superseded by https://github.com/ibuildingsnl/qa-tools-v3/issues/84
